/* empty css                             */
import { c as createAstro, d as createComponent, r as renderTemplate, f as renderComponent, m as maybeRenderHead } from '../astro_TmZg0bPE.mjs';
import 'kleur/colors';
import 'html-escaper';
import { $ as $$Layout } from './Contacto_zJtAwgZx.mjs';
import { $ as $$ParrafosImagenes, a as $$ArticulosRelacionados } from './Informacion_n3-V_5Lx.mjs';
/* empty css                             */

const $$Astro = createAstro();
const $$Tecnicas = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Tecnicas;
  return renderTemplate`${renderComponent($$result, "Layout", $$Layout, { "title": "Tecnicas", "data-astro-cid-qxhwfb5b": true }, { "content": ($$result2) => renderTemplate`${maybeRenderHead()}<article class="flex items-center justify-center max-w-screen xl:mt-0 mt-40 sm:mb-4 lg:mb-4 mx-4 inset-0 bg-[#e0dddd] dark:bg-[#18191d] relative" data-astro-cid-qxhwfb5b> <div class="flex flex-col bg-[#e0dddd] dark:bg-[#18191d] lg:mt-8" data-astro-cid-qxhwfb5b> <main class="flex flex-col md:flex-row sm:flex-row flex-1 overflow-hidden" data-astro-cid-qxhwfb5b> <article class="prose prose-gray mx-auto p-6 max-w-screen md:w-3/4 dark:prose-invert" data-astro-cid-qxhwfb5b> <h1 class="text-4xl font-extrabold tracking-tight lg:text-5xl lg:leading-[3.5rem] dark:text-white" data-astro-cid-qxhwfb5b>
Técnicas
</h1> <p class="text-[#18191d] dark:text-[#e0dddd]" data-astro-cid-qxhwfb5b>En ruART hacemos, con la construcción industrializada, relidad los proyectos constructivos de cualquier tipología y uso.</p> <br data-astro-cid-qxhwfb5b> ${renderComponent($$result2, "ParrafosImagenes", $$ParrafosImagenes, { "titulo": "Residencial: ", "texto": "Conformando cualquier tama\xF1o o tipo de edificio residencial, individual o colectivo. Anexos a construcciones ya existentes, ampliaciones o edificios de servicios en viviendas ya construidas ( gimnasios, apartamentos de invitados, garajes, trasteros,...).", "img1": "./src/assets/galeria/img-1.jpg", "img2": "./src/assets/galeria/img-2.jpg", "data-astro-cid-qxhwfb5b": true })} ${renderComponent($$result2, "ParrafosImagenes", $$ParrafosImagenes, { "titulo": "Dotacional: ", "texto": "Con la construcci\xF3n individualizada podemos abarcar todo tipo de soluciones para servicios p\xFAlblicos, (edificios para parques, colegios, salas de cultura, exposiciones), adaptamos la construcci\xF3n al edificio demandado.", "img1": "./src/assets/galeria/img-3.jpg", "img2": "./src/assets/galeria/img-4.jpg", "data-astro-cid-qxhwfb5b": true })} ${renderComponent($$result2, "ParrafosImagenes", $$ParrafosImagenes, { "titulo": "Comercial: ", "texto": "Podemos fabricar edificios con uso comercial, tales como bares, restaurantes, hoteles, apartamentos vacacionales...", "img1": "./src/assets/galeria/img-5.jpg", "img2": "./src/assets/galeria/img-6.jpg", "data-astro-cid-qxhwfb5b": true })} <p class="text-[#18191d] dark:text-[#e0dddd]" data-astro-cid-qxhwfb5b>
En definitiva, desde ruART, partiendo desde tu idea y con la colaboración de nuestro gabinete técnico formado por ARQUITECTOS e INGENIEROS de reconocido valor profesional, podemos dar forma al proyecto con construcción industrializada y modular, partiendo de nuestras instalaciones para cualquier punto del globo.
</p> </article> <aside class="w-full h-screen-2xl md:w-1/5 p-6 border-l border-black dark:border-white" data-astro-cid-qxhwfb5b> <div class="mb-6" data-astro-cid-qxhwfb5b> <h2 class="text-lg font-semibold dark:text-white" data-astro-cid-qxhwfb5b>Articulos relacionados</h2> <div class="mt-4 space-y-4" data-astro-cid-qxhwfb5b> ${renderComponent($$result2, "ArticulosRelacionados", $$ArticulosRelacionados, { "nombre": "Personalizaci\xF3n", "descripcion": "Breve descripcion del articulo", "alt": "", "imagen": "./src/assets/galeria/img-7.jpg", "enlace": "/Personalizacion", "data-astro-cid-qxhwfb5b": true })} ${renderComponent($$result2, "ArticulosRelacionados", $$ArticulosRelacionados, { "nombre": "Nombre articulo", "descripcion": "Breve descripcion del articulo", "alt": "", "imagen": "./src/assets/galeria/img-8.jpg", "enlace": "/Informacion", "data-astro-cid-qxhwfb5b": true })} ${renderComponent($$result2, "ArticulosRelacionados", $$ArticulosRelacionados, { "nombre": "Nombre articulo", "descripcion": "Breve descripcion del articulo", "alt": "", "imagen": "./src/assets/galeria/img-10.jpg", "enlace": "/QuienesSomos", "data-astro-cid-qxhwfb5b": true })} </div> </div> </aside></main></div> </article>` })} `;
}, "C:/Users/tamenis/Documents/Uned/AstroApp/src/pages/Tecnicas.astro", void 0);

const $$file = "C:/Users/tamenis/Documents/Uned/AstroApp/src/pages/Tecnicas.astro";
const $$url = "/Tecnicas";

export { $$Tecnicas as default, $$file as file, $$url as url };
